openapi: 3.0.3
info:
    title: CS50x Subtitle Generator
    description: CS50x Subtitle Generator APIs
    version: 1.0.0
    contact:
        name: Fady Emad
        url: https://github.com/fady2019
components:
    schemas:
        SignUpInput:
            type: object
            required:
                - first_name
                - last_name
                - username
                - email
                - password
            properties:
                first_name:
                    type: string
                last_name:
                    type: string
                username:
                    type: string
                email:
                    type: string
                password:
                    type: string
        #
        LoginInput:
            type: object
            required:
                - username_or_email
                - password
            properties:
                username_or_email:
                    type: string
                password:
                    type: string
        #
        ChangePasswordInput:
            type: object
            required:
                - current_password
                - new_password
            properties:
                current_password:
                    type: string
                new_password:
                    type: string
        #
        User:
            type: object
            properties:
                id:
                    type: string
                first_name:
                    type: string
                last_name:
                    type: string
                username:
                    type: string
                email:
                    type: string
        #
        Response:
            type: object
            properties:
                message:
                    type: string
        #
        ResponseWithUserData:
            allOf:
                - type: object
                  properties:
                      data:
                          $ref: '#/components/schemas/User'
                - $ref: '#/components/schemas/Response'

    #
    #
    #
    responses:
        SuccessfulAuth:
            description: Success
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            data:
                                $ref: '#/components/schemas/User'
                            message:
                                type: string
        #
        NoDataResponse:
            description: Success
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Response'
        #
        BadRequestError:
            description: Bad Request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Response'
        #
        # UnauthorizedError:
        #     description: Unauthorized
        #     content:
        #         application/json:
        #             schema:
        #                 $ref: '#/components/schemas/Response'
        #
        ForbiddenError:
            description: Forbidden (Require login)
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Response'
        #
        # NotFoundError:
        #     description: Not Found
        #     content:
        #         application/json:
        #             schema:
        #                 $ref: '#/components/schemas/Response'
        #
        # ConflictError:
        #     description: Conflict
        #     content:
        #         application/json:
        #             schema:
        #                 $ref: '#/components/schemas/Response'
        #
        UnprocessableEntityError:
            description: Unprocessable Entity (Invalid input)
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Response'
        #
        ServerError:
            description: Server Issue
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Response'
    #
    #
    #
    # parameters:
